CREATE TABLE Person(
  ID INTEGER UNIQUE NOT NULL primary key,
  NAME VARCHAR(20) NOT NULL
  );
  
CREATE TABLE BIRTHDAY(
  BDAY INTEGER UNIQUE,
  BMONTH INTEGER UNIQUE,
  BYEAR INTEGER UNIQUE,
  PRIMARY KEY (BDAY, BMONTH, BYEAR)
  );
  
CREATE TABLE Customer(
  ID INTEGER UNIQUE NOT NULL PRIMARY KEY,
  PhoneNumber INTEGER NOT NULL,
  BDAY INTEGER,
  BMONTH INTEGER,
  BYEAR INTEGER,
  FOREIGN KEY (ID) REFERENCES Person(ID),
  FOREIGN KEY (BDAY) REFERENCES BIRTHDAY(BDAY),
  FOREIGN KEY (BMONTH) REFERENCES BIRTHDAY(BMONTH),
  FOREIGN KEY (BYEAR) REFERENCES BIRTHDAY(BYEAR)
  );
  
CREATE TABLE Pilot(
  ID INTEGER UNIQUE NOT NULL PRIMARY KEY,
  FOREIGN KEY (ID) REFERENCES Person(ID)
  );
  
CREATE TABLE AirPlane(
  ID INTEGER UNIQUE NOT NULL PRIMARY KEY,
  ManufactureYear INTEGER NOT NULL,
  Model VARCHAR(20) NOT NULL
  );

CREATE TABLE Flight(
  FlightID INTEGER UNIQUE NOT NULL PRIMARY KEY,
  FlightDate INTEGER NOT NULL,
  FlightTime INTEGER NOT NULL,
  AirPlaneID INTEGER NOT NULL,
  FOREIGN KEY (AirPlaneID) REFERENCES AirPlane(ID)
  );

CREATE TABLE Seat(
  SeatRow INTEGER UNIQUE NOT NULL,
  SeatAisle INTEGER UNIQUE NOT NULL,
  PRIMARY KEY(SeatRow, SeatAisle)
  );
  
Create TABLE NormalSeat(
  NormalRow INTEGER UNIQUE NOT NULL,
  NormalAisle INTEGER UNIQUE NOT NULL,
  FOREIGN KEY (NormalRow) REFERENCES Seat(SeatRow),
  FOREIGN KEY (NormalAisle) REFERENCES Seat(SeatAisle),
  PRIMARY KEY(NormalRow, NormalAisle)
  );

Create TABLE VIPSeat(
  VipRow INTEGER UNIQUE NOT NULL,
  VIPAisle INTEGER UNIQUE NOT NULL,
  FOREIGN KEY (VipRow) REFERENCES Seat(SeatRow),
  FOREIGN KEY (VIPAisle) REFERENCES Seat(SeatAisle),
  PRIMARY KEY(VipRow, VIPAisle)
  );
  
CREATE TABLE NormalCustomer(
  ID INTEGER UNIQUE NOT NULL PRIMARY KEY,
  NormalSeatRow INTEGER UNIQUE NOT NULL,
  NormalSeatAisle INTEGER UNIQUE NOT NULL,
  FOREIGN KEY (ID) REFERENCES Customer(ID),
  FOREIGN KEY (NormalSeatRow) REFERENCES NormalSeat(NormalRow),
  FOREIGN KEY (NormalSeatAisle) REFERENCES NormalSeat(NormalAisle)
  );
  
CREATE TABLE VIPCustomer(
  ID INTEGER UNIQUE NOT NULL PRIMARY KEY,
  Points INTEGER NOT NULL,
  SeatRow INTEGER UNIQUE NOT NULL,
  SeatAisle INTEGER UNIQUE NOT NULL,
  FOREIGN KEY (ID) REFERENCES Customer(ID),
  FOREIGN KEY (SeatRow) REFERENCES NormalSeat(NormalRow),
  FOREIGN KEY (SeatAisle) REFERENCES NormalSeat(NormalAisle),
  CHECK (vipcustomer.points>=0)
  );
  
CREATE TABLE FlightInvitation(
  CustomerID INTEGER UNIQUE NOT NULL,
  Price INTEGER NOT NULL,
  FlightID INTEGER UNIQUE NOT NULL,
  PRIMARY KEY(CustomerID, FlightID)
  );
  
CREATE TABLE HasPilots(
  PilotID INTEGER NOT NULL,
  FlightID INTEGER NOT NULL,
  FOREIGN KEY (PilotID) REFERENCES Pilot(ID),
  FOREIGN KEY (FlightID) REFERENCES Flight(FlightID)
  );
