DROP TABLE HasPilots;
DROP TABLE FlightInvitation;
DROP TABLE VIPCustomer;
DROP TABLE NormalCustomer;
DROP TABLE VIPSeat;
DROP TABLE NormalSeat;
DROP TABLE Seat;
DROP TABLE Flight;
DROP TABLE AirPlane;
DROP TABLE Pilot;
DROP TABLE HasBday;
DROP TABLE Customer;
DROP TABLE BIRTHDAY;
DROP TABLE Person;

